---
- hosts: control-plane
  roles:
    - container/crio
    - kubernetes/control-plane

- hosts: k8s-node
  roles:
    - container/crio
    - kubernetes/node

- hosts: control-plane
  roles:
    - cni/flannel
