---
k8s_ansible__package_dependencies:
  - gnupg2
  - apt-transport-https
  - curl

iptables_legacy_binary:
  - iptables
  - arptables
  - ebtables

iptables_legacy:
  - name: "iptables"
    path: "/usr/sbin/iptables-legacy"
  - name: "ip6tables"
    path: "/usr/sbin/ip6tables-legacy"
  - name: "arptables"
    path: "/usr/sbin/arptables-legacy"
  - name: "ebtables"
    path: "/usr/sbin/ebtables-legacy"
