---
- name: Check if CRIO is installed
  shell: dpkg -l | grep cri-o
  register: dpkg_search_crio
  failed_when: dpkg_search_crio.rc not in [0, 1]
  changed_when: false

- block:
  - name: Add kubic apt key
    apt_key:
      url: "{{ crio__kubic_apt_key }}"
      state: present
    register: result
    until: result is succeeded
  
  - name: Add kubic cri-o apt key
    apt_key:
      url: "{{ crio__kubic_crio_apt_key }}"
      state: present
    register: result
    until: result is succeeded

  - name: Add kubic apt repo
    apt_repository:
      repo: "{{ crio__kubic_apt_repo }}"
      state: present
      filename: "devel:kubic:libcontainers:stable.list"
    register: result
    until: result is succeeded
  
  - name: Add kubic cri-o apt repo
    apt_repository:
      repo: "{{ crio__kubic_crio_apt_repo }}"
      state: present
      filename: "devel:kubic:libcontainers:stable:cri-o:{{ crio__version }}.list"
    register: result
    until: result is succeeded
    
  - name: apt update
    apt:
      update_cache: yes

  - name: Install CRI-O
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - cri-o
      - cri-o-runc
  
  - name: Disable metacopy option
    lineinfile:
      path: /etc/containers/storage.conf
      regexp: '^mountopt = '
      line: mountopt = "nodev"
    notify:
      - restart_crio

  when: dpkg_search_crio.rc == 1
