---
- name: "Verify if {{ module.name }} loaded"
  shell: lsmod | grep {{ module.name }}
  register: lsmod_result
  failed_when: lsmod_result.rc not in [0, 1]
  changed_when: false

- name: "Enable {{ module.name }} module"
  modprobe:
    name: "{{ module.name }}"
    state: present
  when: lsmod_result.rc == 1

- name: "Persist {{ module.name }} module"
  copy:
    dest: "/etc/modules-load.d/{{ module.name }}.conf"
    content: "{{ module.name }}"
  when: lsmod_result.rc == 1
