---
- name: Install role dependencies
  package:
    name: "{{ kubernetes__package_dependencies }}"
  register: result
  until: result is succeeded

- name: Add kubic kubernetes apt key
  apt_key:
    url: "{{ kubernetes__apt_key }}"
    state: present
  register: result
  until: result is succeeded

- name: Add kubernetes apt repo
  apt_repository:
    repo: "{{ kubernetes__apt_repo }}"
    state: present
    filename: "kubernetes.list"
  register: result
  until: result is succeeded

- name: apt update
  apt:
    update_cache: yes