---
- name: Check if flannel container already exists
  command: kubectl get pod -n kube-system
  environment:
    KUBECONFIG: "{{ kubectl__cluster_config_path }}"
  changed_when: False
  register: flannel_pods

- block:
  - name: Download flannel manifest
    get_url:
      url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
      dest: /tmp
      mode: '0644'
    register: result
    until: result is succeeded

  - name: Deploy flannel
    k8s:
      src: /tmp/kube-flannel.yml
      state: present
    environment:
      KUBECONFIG: "{{ kubectl__cluster_config_path }}"
    register: result
    until: result is succeeded
  
  when: '"kube-flannel-ds-" not in flannel_pods.stdout'
