---
- name: Restart kubelet.service
  systemd:
    name: kubelet.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  listen:
    - restart_kubelet

- name: apt update
  apt:
    update_cache: yes
  listen:
    - apt_update
