---
- name: Check
  shell: "kubectl get pod -n kube-system"
  become_user: "{{ k8s_ctrl_user__name }}"
  changed_when: False
  register: kubectl_get_pod

# ココ脳死で書いた
- name: Deploy CNI plugin
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  become_user: "{{ k8s_ctrl_user__name }}"
  when: kubectl_get_pod.stdout.find("kube-flannel-ds-") == -1
  register: result
  until: result is succeeded
