---
- name: Create .kube
  file:
    path: "{{ controller_home_dir }}/.kube"
    state: directory
  become_user: "{{ k8s_ctrl_user__name }}"
  register: result
  until: result is succeeded

- name: Check if k8s config file exists
  stat:
    path: "{{ controller_home_dir }}/.kube/config"
  register: k8s_config_file

- block:
  - name: move k8s config
    shell: "cp -i /etc/kubernetes/admin.conf {{ controller_home_dir }}/.kube/config"
    register: result
    until: result is succeeded

  - name: get user id
    shell: "id -u"
    become_user: "{{ k8s_ctrl_user__name }}"
    register: user_id

  - name: get group id
    shell: "id -g"
    become_user: "{{ k8s_ctrl_user__name }}"
    register: group_id

  - name: change permission
    shell: "chown {{ user_id.stdout }}:{{ group_id.stdout }} {{ controller_home_dir }}/.kube/config"
    register: result
    until: result is succeeded
  
  when: k8s_config_file.stat.exists == False

