---
- name: Install k8s dependencies packages
  apt:
    pkg: "{{ k8s_ansible__package_dependencies }}"
    state: present
    update_cache: yes
  register: result
  until: result is succeeded

- name: Install k8s module dependencies packages
  import_tasks: ansible_module.yml
  when: k8s__role == "master"
