---
- name: Install k8s dependencies packages
  import_tasks: install.yml

- name: Prevent iptables from using the nftables backend
  import_tasks: iptables.yml

- name: Install and Setup edieter
  import_tasks: editer.yml

- name: Disables swap for Kubernetes node
  import_tasks: swapoff.yml

- name: Set hosts
  import_tasks: hosts.yml
