---
- name: Install VIM
  package:
    name: vim
    state: present
  register: result
  until: result is succeeded

- name: Config default editor to VIM
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Disables swap for Kubernetes node
  import_tasks: swapoff.yml
