---
- name: Install VIM
  package:
    name: vim
    state: present
  register: result
  until: result is succeeded

- name: Config default editor to VIM
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Install apt-transport-https
  package:
    name: apt-transport-https
    state: present
  register: result
  until: result is succeeded

- name: Letting iptables see bridged traffic
  import_tasks: iptables.yml

- name: Verify br_netfilter module path exists
  file:
    path: /etc/modules-load.d
    state: directory

- include: crio_module.yml
  with_items:
    - name: overlay
    - name: br_netfilter
  loop_control:
    loop_var: module

- name: Disables swap for Kubernetes node
  import_tasks: swapoff.yml