---
- name: Create kubernetes join shell
  shell:
    cmd: kubeadm token create --print-join-command | grep kubeadm
  register: kubeadm_print_join_command

- name: Create kubelet config directory
  file:
    path: "{{ playbook_dir }}/roles/kubernetes-node/files"
    state: directory
  become: false
  run_once: true
  delegate_to: localhost

- name: Create script to join kubernetes
  copy:
    dest: "{{ playbook_dir }}/roles/kubernetes-node/files/k8s_cluster_join.sh"
    content: |
      #!/bin/sh
      {{ kubeadm_print_join_command.stdout }}
    mode: '0755'
  become: false
  run_once: true
  delegate_to: localhost