---
- name: Place file to join kubernetes cluster
  copy:
    src: "k8s_join_{{ lookup('pipe','date +%Y%m%d') }}.sh"
    dest: "/etc/kubernetes/k8s_join_{{ lookup('pipe','date +%Y%m%d') }}.sh"
    mode: '0755'
  register: result
  until: result is succeeded

- name: Join kubernetes Cluster
  shell:
    cmd: "/etc/kubernetes/k8s_join_{{ lookup('pipe','date +%Y%m%d') }}.sh"
  register: result
  until: result is succeeded
